 version: 1
  applications:
    - frontend:
        phases:
            preBuild:
            commands:
                - yarn install
            build:
            commands:
                - cd layers/experience/clients/web/marketing
                - cat package.json
                - yarn build
        artifacts:
            baseDirectory: layers/experience/clients/web/marketing/build
            files:
            - '**/*'
        cache:
            paths:
            - node_modules/**/*
        buildPath: /
        appRoot: layers/experience/clients/web/marketing